# Generated by Django 5.2.1 on 2025-07-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='flota.vehiculo', verbose_name='Vehículo'),
        ),
    ]
