# Generated by Django 5.2.1 on 2025-07-03 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_reserva_vehiculo'),
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ENTREGA', 'Entrega'), ('REEMPLAZO', 'Reemplazo'), ('DEVOLUCION', 'Devolución')], max_length=16)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('kilometraje', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='checklists/fotos/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='alquiler.contrato')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContratoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('modo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('REEMPLAZO', 'Reemplazo')], default='PRINCIPAL', max_length=16)),
                ('fecha_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_historial', to='alquiler.contrato')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_historial', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de Vehículo en Contrato',
                'verbose_name_plural': 'Historial de Vehículos en Contrato',
                'ordering': ['contrato', '-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='¿Entrega a domicilio?')),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_devolucion', models.CharField(blank=True, max_length=255, null=True)),
                ('chofer', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de delivery')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='alquiler.contrato')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
