# Generated by Django 5.2.1 on 2025-07-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_extra_checklist_contratovehiculo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='alquiler.extra', verbose_name='Extras contratados'),
        ),
    ]
