# Generated by Django 5.2.1 on 2025-07-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_contrato_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='alquiler.cliente', verbose_name='Cliente directo'),
        ),
    ]
