# Generated by Django 5.2.1 on 2025-07-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_contrato_cliente'),
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={},
        ),
        migrations.AddField(
            model_name='contrato',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='flota.vehiculo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='alquiler.extra'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='terminos_condiciones',
            field=models.TextField(blank=True),
        ),
    ]
