# Generated by Django 5.2.1 on 2025-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_contrato_descuento_porcentaje_contrato_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='garantia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de garantía exigida en el contrato.', max_digits=10, verbose_name='Garantía'),
        ),
    ]
