# Generated by Django 5.2.1 on 2025-07-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_contrato_garantia'),
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='alquiler.contrato')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Período de Contrato',
                'verbose_name_plural': 'Períodos de Contrato',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
