# Generated by Django 5.2.1 on 2025-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0009_contratoperiodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Costo de delivery'),
        ),
    ]
