# Generated by Django 5.2.1 on 2025-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=20, verbose_name='Transmisión')),
                ('capacidad_pasajeros', models.PositiveSmallIntegerField(verbose_name='Capacidad de Pasajeros')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_USO', 'En Uso'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa Diaria')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
