# Generated by Django 5.2.1 on 2025-06-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='año',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad_pasajeros',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tarifa_diaria',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_homologacion',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/homologacion/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_permiso_circulacion',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/permiso_circulacion/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_rev_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/rev_tecnica/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='archivo_soap',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/soap/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad de carga (kg) o pasajeros', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('BENCINA', 'Bencina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido'), ('GNC', 'Gas Natural'), ('GLP', 'Gas Licuado'), ('OTRO', 'Otro')], default='Diesel', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_homologacion',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Homologación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_permiso_circulacion',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Permiso Circulación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_rev_tecnica',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Rev. Técnica'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vencimiento_soap',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento SOAP'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_asientos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(default='ABC123', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_ARRIENDO', 'En arriendo'), ('EN_REEMPLAZO', 'En reemplazo'), ('EN_REPARACION', 'En reparación'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('DADO_BAJA', 'Dado de baja'), ('EN_EQUIPAMIENTO', 'En equipamiento'), ('EN_TRANSITO', 'En tránsito'), ('MANTENIMIENTO_ATRASADO', 'Mantenimiento atrasado'), ('PROX_MANTENIMIENTO', 'Próx. a mantenimiento'), ('EN_OBSERVACION', 'En observación')], default='DISPONIBLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], max_length=16),
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOAP', 'SOAP'), ('REV_TECNICA', 'Revisión Técnica'), ('PERMISO_CIRCULACION', 'Permiso de Circulación'), ('HOMOLOGACION', 'Homologación'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('descripcion', models.CharField(blank=True, max_length=128)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='vehiculos/documentos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='flota.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de modelo')),
                ('tipo', models.CharField(choices=[('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='flota.marca')),
            ],
            options={
                'unique_together': {('marca', 'nombre', 'anio')},
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='flota.modelovehiculo'),
        ),
    ]
