# Generated by Django 5.2.1 on 2025-06-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_grupovehiculo_vehiculo_tenencia_vehiculo_traccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelovehiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='tipo_carroceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='flota.tipocarroceria'),
        ),
    ]
