# Generated by Django 5.2.1 on 2025-06-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_tipocarroceria_remove_modelovehiculo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelovehiculo',
            name='tipo_carroceria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='flota.tipocarroceria'),
            preserve_default=False,
        ),
    ]
