# Generated by Django 5.2.1 on 2025-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_alter_modelovehiculo_tipo_carroceria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado_general',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_ARRIENDO', 'En arriendo'), ('EN_REEMPLAZO', 'En reemplazo'), ('DADO_BAJA', 'Dado de baja'), ('LIBRE', 'Libre')], default='LIBRE', max_length=20, verbose_name='Estado general'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='subestado',
            field=models.CharField(choices=[('NINGUNO', 'Sin subestado'), ('EN_REPARACION', 'En reparación'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('EN_EQUIPAMIENTO', 'En equipamiento'), ('EN_TRANSITO', 'En tránsito'), ('MANTENIMIENTO_ATRASADO', 'Mantenimiento atrasado'), ('PROX_MANTENIMIENTO', 'Próx. a mantenimiento'), ('EN_OBSERVACION', 'En observación')], default='NINGUNO', max_length=30, verbose_name='Subestado'),
        ),
    ]
