# Generated by Django 5.2.1 on 2025-06-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
        ('flota', '0006_remove_vehiculo_estado_vehiculo_estado_general_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KilometrajeVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('kilometraje', models.PositiveIntegerField()),
                ('tipo_evento', models.CharField(choices=[('LECTURA', 'Lectura periódica'), ('ENTREGA', 'Entrega a cliente'), ('DEVOLUCION', 'Devolución de cliente'), ('MANTENIMIENTO', 'Ingreso a mantenimiento'), ('SALIDA_MANTENIMIENTO', 'Salida de mantenimiento'), ('AJUSTE', 'Ajuste administrativo')], max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_general', models.CharField(blank=True, editable=False, max_length=20)),
                ('subestado', models.CharField(blank=True, editable=False, max_length=30)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquiler.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_kilometraje', to='flota.vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
