# Generated by Django 5.2.1 on 2025-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_kilometrajevehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='proximo_mantenimiento',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje al que corresponde el próximo mantenimiento', null=True),
        ),
    ]
