# Generated by Django 5.2.1 on 2025-06-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('telefono', models.CharField(blank=True, max_length=32, null=True)),
                ('contacto', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('es_preventivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de entrada al taller')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida del taller')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=16)),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=64, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='flota.vehiculo')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.taller')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.itemrepuesto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_utilizados', to='mantenimiento.ordenmantenimiento')),
            ],
        ),
    ]
