# Generated by Django 5.2.1 on 2025-06-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32)),
                ('descripcion', models.CharField(max_length=256)),
                ('unidades', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='mantenimiento.ordenmantenimiento')),
            ],
        ),
    ]
