# Generated by Django 5.2.1 on 2025-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_ordeningreso_trabajosolicitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='kilometraje_ingreso_mantenimiento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje ingreso mantenimiento'),
        ),
        migrations.AddField(
            model_name='trabajorealizado',
            name='componente',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Transmisión', 'Transmisión'), ('Chasis', 'Chasis'), ('Suspensión', 'Suspensión'), ('Frenos', 'Frenos'), ('Dirección', 'Dirección'), ('Sistema Eléctrico', 'Sistema Eléctrico'), ('Carrocería', 'Carrocería'), ('Neumáticos', 'Neumáticos'), ('Sistema de Escape', 'Sistema de Escape'), ('Otro', 'Otro')], default='Otro', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajorealizado',
            name='valor',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='descripcion_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del ingreso'),
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='unidades',
            field=models.PositiveIntegerField(),
        ),
    ]
