# Generated by Django 5.2.1 on 2025-07-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_vehiculo_proximo_mantenimiento'),
        ('mantenimiento', '0004_remove_trabajorealizado_valor_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenmantenimiento',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='ordenmantenimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ordenmantenimiento',
            name='tecnico_responsable',
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Nº Orden'),
        ),
        migrations.AddField(
            model_name='trabajorealizado',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='descripcion_problema',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones del Ingreso'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='kilometraje_ingreso_mantenimiento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tipomantenimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.vehiculo'),
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='componente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='RepuestoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.ordenmantenimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumoRepuesto',
        ),
        migrations.DeleteModel(
            name='ItemRepuesto',
        ),
    ]
