# Generated by Django 5.2.1 on 2025-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_auto_add_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajorealizado',
            name='componente',
            field=models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('chasis', 'Chasis'), ('suspension', 'Suspensión'), ('frenos', 'Frenos'), ('direccion', 'Dirección'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('neumaticos', 'Neumáticos'), ('escape', 'Sistema de Escape'), ('otro', 'Otro')], max_length=100),
        ),
    ]
