# Generated by Django 5.2.1 on 2025-07-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_alter_trabajorealizado_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeningreso',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.taller'),
        ),
    ]
