# Generated by Django 5.2.1 on 2025-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_ordeningreso_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeningreso',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordeningreso',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje actual'),
        ),
    ]
