# Generated by Django 5.2.1 on 2025-07-02 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_ordeningreso_estado_ordeningreso_kilometraje_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='contacto',
        ),
        migrations.AddField(
            model_name='taller',
            name='comuna',
            field=models.CharField(default='Por completar', max_length=64, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='dias_horarios',
            field=models.CharField(default='Por completar', max_length=128, verbose_name='Días y horarios de atención'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='taller',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('REVISION', 'En revisión')], default='ACTIVO', max_length=16, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='giro_comercial',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Giro comercial'),
        ),
        migrations.AddField(
            model_name='taller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='talleres/logos/', verbose_name='Logo/foto del taller'),
        ),
        migrations.AddField(
            model_name='taller',
            name='razon_social',
            field=models.CharField(default='Por Completar', max_length=128, verbose_name='Razón Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Redes sociales'),
        ),
        migrations.AddField(
            model_name='taller',
            name='region',
            field=models.CharField(default='Por Completar', max_length=64, verbose_name='Región'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='taller',
            name='rut',
            field=models.CharField(default='Por completar', max_length=20, verbose_name='RUT de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='rut_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT representante legal'),
        ),
        migrations.AddField(
            model_name='taller',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='taller',
            name='tipos_servicio',
            field=models.CharField(default='Por completar', help_text='Ejemplo: mecánica general, electricidad, frenos, etc. (separados por coma)', max_length=200, verbose_name='Tipos de servicios ofrecidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taller',
            name='ubicacion_mapa',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ubicación mapa (embed o link)'),
        ),
        migrations.AddField(
            model_name='taller',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(default='Por completar', max_length=256, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre de fantasía / comercial'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='telefono',
            field=models.CharField(default='Por Completar', max_length=32, verbose_name='Teléfono de contacto'),
            preserve_default=False,
        ),
    ]
